### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by CheezBallzPi** [RoboEagles4828/ACE#31]
We need a changelog for the `master` branch.

**Comment by P1n3appl3** [comment]
Do you mean in the releases section? if so i can go make those more pretty and informational.

**Comment by alebcay** [comment]
Yes, he meant that. Although ideally, we'd have a script or something to do it per release in the future.

**Comment by P1n3appl3** [comment]
Check out what I did with it, do y'all think that's good @CheezBallzPi and @alebcay and if not what should be different? Also should we append the version numbers with -alpha while it's on the test chassis and -beta while it's on the main one but before its released?

**Comment by CheezBallzPi** [comment]
@P1n3appl3 I was actually thinking of a file with everything we change per release, so we don't have to dig around to find what we did. It's basically what you have currently, but in a file instead. We can add stuff on it as we go.

**Comment by CheezBallzPi** [comment]
Sorry for the crappy issue, I was in a hurry.

**Comment by alebcay** [comment]
> @P1n3appl3 I was actually thinking of a file with everything we change per release, so we don't have to dig around to find what we did. It's basically what you have currently, but in a file instead. We can add stuff on it as we go.

A quick way would be `git log --pretty=oneline [SHA1_of_last_release]..HEAD > CHANGES`, which would create a file `CHANGES`.

**Comment by CheezBallzPi** [comment]
It shouldn't be too hard to manually write it. We would have to remove the extra commits (merging, bugfixes) anyway.
